#pragma once

// Application icon
#define IDI_APP_ICON 101

// Logo bitmap
#define IDB_PNG1 102

// Dialogs
#define IDD_SEARCH_DIALOG 103
#define IDD_LOADING_DIALOG 104
#define IDD_APP_DETAILS 105

// Loading dialog controls
#define IDC_LOADING_ANIMATE 210
#define IDC_LOADING_TEXT 211
#define IDC_LOADING_ICON 212

// Search dialog controls
#define IDC_SEARCH_CATEGORY 201
#define IDC_SEARCH_APP 202
#define IDC_CASE_INSENSITIVE 203
#define IDC_CASE_SENSITIVE 204
#define IDC_CONTAINS 205
#define IDC_EXACT_MATCH 206
#define IDC_USE_REGEX 207
#define IDC_SEARCH_ALL 208
#define IDC_REFINE_RESULTS 209

// App details dialog controls
#define IDC_APP_ICON 301
#define IDC_APP_NAME 302
#define IDC_APP_PUBLISHER 303
#define IDC_APP_VERSION 304
#define IDC_APP_PACKAGE_ID 305
#define IDC_APP_SOURCE 306
#define IDC_APP_STATUS 307
#define IDC_APP_DESCRIPTION 308
#define IDC_APP_HOMEPAGE 309
#define IDC_APP_LICENSE 310
#define IDC_APP_INSTALLER 311
#define IDC_APP_ARCH 312
#define IDC_APP_TAGS 313
#define IDC_BTN_INSTALL 314
#define IDC_BTN_UNINSTALL 315
#define IDC_BTN_REINSTALL 316
// App details static labels
#define IDC_LABEL_PUBLISHER 317
#define IDC_LABEL_VERSION 318
#define IDC_LABEL_PACKAGE_ID 319
#define IDC_LABEL_SOURCE 321
#define IDC_LABEL_STATUS 322
#define IDC_GROUPBOX_DESCRIPTION 323
#define IDC_GROUPBOX_TECHNICAL 324
#define IDC_LABEL_HOMEPAGE 325
#define IDC_LABEL_LICENSE 326
#define IDC_LABEL_INSTALLER_TYPE 327
#define IDC_LABEL_ARCHITECTURE 328
#define IDC_LABEL_TAGS 329

// Confirmation dialog
#define IDD_CONFIRM_ACTION 107
#define IDC_CONFIRM_MESSAGE 330

// Accelerators
#define IDR_ACCELERATOR1 108
#define ID_ACCEL_QUIT 1011

